version: "3.9"
services:
  secretnode:
    image: ghcr.io/scrtlabs/localsecret:v1.9.0-beta.1-random
    #build:
    #  context: ..
    #  dockerfile: Dockerfile
    #  target: build-localsecret
    #  args:
    #    FEATURES: "${FEATURES},debug-print"
    #    FEATURES_U: ${FEATURES_U}
    #    SGX_MODE: SW
    #    SECRET_NODE_TYPE: BOOTSTRAP
    #    CHAIN_ID: secretdev-1
    #    IAS_BUILD: sw_dummy
    #  secrets:
    #    - API_KEY
    #    - SPID
    # ports are only here in case interaction
    # between localhost and container is desired
    ports:
      - "26657:26657"
      - "26656:26656"
      - "9090:9090"
      - "9091:9091"
      - "1317:1317"
      # faucet
      - "5000:5000"
    healthcheck:
      test: ["CMD-SHELL", "secretd status"]
      interval: 10s
      timeout: 5s
      retries: 5
  integration-tests:
    build:
      context: .
      dockerfile: Dockerfile
      target: integration-tests
      args:
        SECRETNODE_HOSTNAME: secretnode
    depends_on:
      secretnode:
        condition: service_healthy
