name: Deploy to Localsecret Dev Environment

on:
  workflow_run:
    workflows: ["Integration Tests"]
    types:
      - completed


env:
  LOCALSECRET: localsecret.dvbxbbc9c7fbepev.eastus.azurecontainer.io

jobs:
  Deploy-To-Devenv:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    runs-on: ubuntu-latest
    needs: [Build-LocalSecret, Build-Hermes]
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: integration-completed
      - name: Check artifact
        run: |
          if [ ! -f "integration-completed.txt" ]; then
            echo "Integration tests not completed successfully."
            exit 1
          fi

      - uses: actions/checkout@v3
      - uses: ./.github/actions/install-rust
        with:
          toolchain: 1.63.0
      - name: Add wasm toolchain
        run: |
          rustup target add wasm32-unknown-unknown
      - name: Compile code
        run: make build-mainnet
      - name: Deploy to remote & run integration tests
        run: |
          LOCALSECRET=${{ env.LOCALSECRET }} npx ts-node tests/integration.ts
